### ISSUE TITLE
Solidifying the JavaScript approach

### ISSUE THREAD

**Issue by erikjung** [cloudfour/cloudfour.com-patterns#194]
### Overview

The [JavaScript](https://github.com/cloudfour/cloudfour.com-patterns/tree/master/src/assets/toolkit/scripts) for this pattern library currently consists of:
- Proof-of-concept modules for low-level utility things (like object merging and DOM iteration)
- Some modules for animation-related things (used only by the Sky/Nav component)
- Some component modules that evolved from sandbox demos (Sky, FloatLabel)
- Externals: a custom Modernizr build, svgxuse

```
src/assets/toolkit/scripts/
├── lib
│   ├── component
│   │   ├── float-label.js
│   │   └── sky.js
│   ├── dom
│   │   ├── attributes.js
│   │   └── core.js
│   ├── fx
│   │   ├── easing.js
│   │   └── tween.js
│   └── util
│       └── object.js
└── toolkit.js
```

What it currently lacks:
- DOM library
- Polyfills 
- Any system for routing (or initializing things on specific pages)
#### Polyfills or modules for things like `classList` and `Object.assign`?

IMO, polyfills are a better solution. I would look into what http://polyfill.io has to offer. We can either include the hosted script, or directly bundle in the specific polyfills used for each feature we depend on.
#### Is Modernizr still the best feature detection solution?

@tylersticka pointed out a potential alternative: http://featurejs.com. 

It differs from Modernizr in a few ways:
- It doesn't auto-run its tests when the page loads (they are executed [cleverly](https://github.com/viljamis/feature.js/blob/master/feature.js#L81-L84) upon first access)
- It doesn't automatically add classes to the `<html>` element (we would need to do that if needed)
- It is smaller in scope for what you can detect
- It is smaller in file size 

I think `feature.js` would be a fine fit. Even though we already have a system in place for Modernizr, we aren't really _using_ many of the feature detections yet, so the transition should be mostly reductive.
#### Do we need a DOM library?

We've been getting by without one, but I'm not sure. Some things to consider:
- We currently only have two components that need JS.
- Will we need more complex DOM scripting as complete pages start coming together?
- Will we need any async request handling?
- Are we sacrificing consistency by rolling our own DOM manipulations? ([example](https://github.com/cloudfour/cloudfour.com-patterns/blob/master/src/assets/toolkit/scripts/lib/dom/attributes.js))
- If using a library, it may need some webpack finessing

FWIW, I think [Bliss](http://blissfuljs.com) looks like a nice fit, if we decide to use anything. I believe the consensus is that jQuery is too hefty, but I'm not 100% sure on that.
### TODOs
- [x] Remove the stuff we aren't using (looking in the `lib` directory)
- [x] Decide on the inclusion of a DOM library
- [x] Decide on the feature detection library. If using `feature.js`:
  - [x] Remove Modernizr script
  - [x] Remove Modernizr Gulp integrations
  - [x] Update existing instances of Modernizr usage in the JS (if any)

/CC @tylersticka @saralohr @nicolemors
