### ISSUE TITLE
CSS theme and custom property organization is needed

### ISSUE THREAD

**Issue by erikjung** [cloudfour/cloudfour.com-patterns#32]
We currently have `theme.css` and `theme-map.css`.
#### theme.css

> This defines the theme in fundamental terms, but not how it is applied to
> the components. That is done in `theme-map.css`.
> https://github.com/suitcss/theme/blob/master/lib/theme.css

Our `themes.css` looks pretty good currently. It's very low-level and mentions no component or content specifics. Our `theme-map.css` is almost empty, which is what we should address next.
#### theme-map.css

The purpose of this file is to **map** the abstract custom properties from `theme.css` into more specifically named groups. And from those more specific groupings, we can have a basis for our even more specific component properties. For example:

``` css
/* theme.css */
:root {
  --color-black: #222;
}

:root {
  --spacing: 1rem;
  --spacing-sm: .5rem;
}
```

``` css
/* theme-map.css */
:root {
  --base-color: var(--color-black);
}

:root {
  --component-spacing: var(--spacing-sm);
}
```

``` css
/* some-component.css */
:root {
  --SomeComponent-color: var(--base-color);
  --SomeComponent-padding: var(--component-spacing);
}
```

---
#### Tasks

We currently have a small but growing number of components that define their own custom properties, but with many values being repeated in multiple files. We need to replace those values with `var()` references to properties within `theme-map.css`.
- [x] Come up with a sensible convention for grouping and naming properties in the theme map
- [ ] Come up with a sensible convention for what can or cannot go into the theme map
  - For example, _no new values may occur, properties must only reference values from `theme.css`_
- [x] Replace static component properties with references to the theme map (where applicable)
