### ISSUE TITLE
Simplify home animation once Chromium issue 750252 is resolved 

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#426]
## Overview

The homepage animation was altered to account for [a Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=750252) involving SVG masks. That issue has been prioritized for a timely release, which means at some point we'll want to simplify that asset so all users can continue to experience some sweet animation.

## Tasks

- [x] ~Remove~ Refine Chromium sniffing
- [x] Remove `u-hidden js-show` from screen content
- [x] Remove second fallback `<g>`
- [x] Remove logic related to newly unnecessary `js-show` and `js-remove` elements
- [x] Re-minify asset using filesize gains from newer `uglifyjs` CLI (which helped offset the cost of including browser sniffing and extra elements)

For extra credit, use this as an opportunity to address #416 and/or #334.

---

See: #423 #424 #425 
See: https://bugs.chromium.org/p/chromium/issues/detail?id=750252

**Comment by tylersticka** [comment]
Unfortunately, while this issue has been marked as `fixed` I'm still seeing pixels being leaked. So I've updated the issue: https://bugs.chromium.org/p/chromium/issues/detail?id=750252#c28
