### ISSUE TITLE
Set up dev branch

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#464]
We need a new branch to use for the next major version. Because our environment will be completely changing, it will probably be easier to make a "clean break" from the previous iteration than to try to adapt the existing structure to new tools and goals.

The end result should be a "fresh" branch of this repo we can begin making changes in to suit this new project.

## Tasks

- [x] Choose a branch name
- [x] Remove or somehow quarantine existing `src` contents (Unsure if this is a `git rm` situation or a good fit for [an orphan branch](https://stackoverflow.com/questions/1384325/in-git-is-there-a-simple-way-of-introducing-an-unrelated-branch-to-a-repository)?)
- [x] Update `package.json`
  - [x] [Version](https://semver.org/) (Keep the `0.x` version for now or use prerelease suffixes?)
  - [x] Uninstall/remove old dependencies
  - [x] Remove old scripts
- [x] Update outdated root configuration files as needed
- [x] Remove unnecessary root configuration files as needed (`.nvmrc`, for example)

**Comment by tylersticka** [comment]
I think removing files is the way to go over an orphan branch, since an orphan branch does not contain the history of its predecessors.

**Comment by tylersticka** [comment]
@cloudfour/dev Is `dev` an acceptable branch name, or should it be something else?

**Comment by spaceninja** [comment]
Is this branch intended for ongoing development? e.g., will it _always_ be the process for people to make feature branches from `dev`, and then periodically we "release" `dev` back into `master`?

In this case, what you're describing is Git Flow, and `dev` is the standard name.

Or will this branch only live as long as we're developing the new version, at which point it gets merged to `master` and deleted?

In this case, `dev` is a bit misleading, and I'd recommend calling it something like `v-next` or `v2` or something that communicates that this is the branch for working on the next version.

**Comment by tylersticka** [comment]
I think the latter is more along the lines of what I was thinking! We can revisit if a multi-step release process is the way to go further along (if that's okay).

**Comment by spaceninja** [comment]
For sure, both are valid approaches. They're just solving different problems. Given that you're creating a branch specifically for this version, I'd recommend naming it along those lines.

**Comment by tylersticka** [comment]
I've created a branch called `v-next`. It is very barren right now! https://github.com/cloudfour/cloudfour.com-patterns/tree/v-next

I have also set this up as a protected branch to discourage unintentional merges, deletions, etc.
