### ISSUE TITLE
Refined color palette

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#468]
<img width="908" alt="Screen Shot 2020-02-19 at 4 54 31 PM" src="https://user-images.githubusercontent.com/69633/74890336-94ec2780-5338-11ea-80b9-c2ee9d6cafb6.png">

## Goal

Revise and expand our existing color palette to improve visual fidelity across devices, clarify usage and promote accessible contrast. This may be a good fit for a design tool like Sketch, Figma or Adobe XD?

This revised palette should be iterated on over time, so we should not let it paralyze our progress.

## Tasks

- [x] Define new alpha-transparent dark/black and light/white values for text on light or dark containers to differentiate from links and emphasized elements
- [x] Revise core blue
  - [x] Should have adequate text contrast on white background _and_ as background for light/white text (see above)
  - [x] Should appear less "dusty purple" on cheap monitors (could use a pinch more green?)
- [x] Revise accent colors
  - [x] Identify those suitable for text
  - [x] Identify those suitable for accents/illustrations
- [x] Include dark and light value variations for all colors in palette
- [x] Test all colors on devices in our lab
- [x] Organize our palette as a YAML file which may displayed in Storybook and consumed from Sass, etc. via [Theo](https://github.com/salesforce-ux/theo). (This may make more sense as a separate task.)

---

@cloudfour/design

**Comment by tylersticka** [comment]
A couple of un-tested color explorations as springboards (left of the vertical rule is "before")...

![Color Progress](https://user-images.githubusercontent.com/69633/74993935-7d2ca600-5401-11ea-99ef-a7799a603ac2.png)

![Contrast](https://user-images.githubusercontent.com/69633/74993955-8ae22b80-5401-11ea-9cbe-bad74c885e76.png)

**Comment by dromo77** [comment]
I’ve been doing some explorations of our color palette. I wanted to summarize what I’ve been working on and see what others think.

The issues these explorations address are:

## Revise core blue
There are two main concerns with our current blue. One is that it can appear purple on cheap monitors. It also fails to meet WCAG contrast standards in areas with a gray background like our footer. I used our current blue as a starting point and created a range of colors that are increasingly more green. I also explored darker values. The blue I think works best is a little less purple, but not too far from the original color. It’s also slightly darker to meet WCAG standards. Here’s our current blue and the one I think we should use moving forward:

<img width="348" alt="blue" src="https://user-images.githubusercontent.com/42841342/75298396-38c94d80-57e7-11ea-8793-56239c928716.png">

## Revise accent colors
I did similar explorations for each of our existing accent colors that focused on exploring warmer and cooler variations for each color. Tyler also did some explorations that used the color purple. I combined our explorations and came up with a revised color palette.

<img width="574" alt="current colors" src="https://user-images.githubusercontent.com/42841342/75298509-8ba30500-57e7-11ea-8dde-1bd35de107f0.png">
<img width="426" alt="proposed-colors" src="https://user-images.githubusercontent.com/42841342/75298444-5dbdc080-57e7-11ea-92c1-99fb0545bfbc.png">

## Include dark and light values for all colors in palette
We already use some dark and light variations of our colors. However they range in value and some of our colors don’t have any variations at all. I tried to create a more cohesive range of colors with similar value steps. The increased number of colors should also give us more options.

<img width="369" alt="color range" src="https://user-images.githubusercontent.com/42841342/75298573-b4c39580-57e7-11ea-8504-ea1cf4b36692.png">

## Define new alpha-transparent dark/black and light/white values for text
Our current text colors are pure black and white. I explored the use of different alpha transparencies for these text colors. The differences are slight, but the transparency should help to create a less stark contrast between text and surrounding elements. It will also help elements, like buttons, that don’t have text transparency applied to pop more.

### Light/white text

<img width="1320" alt="light-text-current" src="https://user-images.githubusercontent.com/42841342/75298948-a1fd9080-57e8-11ea-8f59-ee95a7825e6b.png">
<img width="1334" alt="light-text-proposed" src="https://user-images.githubusercontent.com/42841342/75298950-a32ebd80-57e8-11ea-8908-6d142518e8f4.png">

### Dark/black text

<img width="1306" alt="dark-text-current" src="https://user-images.githubusercontent.com/42841342/75299003-c9545d80-57e8-11ea-9738-def2b981efb1.png">
<img width="1323" alt="dark-text-proposed" src="https://user-images.githubusercontent.com/42841342/75299011-cb1e2100-57e8-11ea-851c-7164bea13d96.png">

**Comment by tylersticka** [comment]
I already had a chance to discuss these color palette updates with @dromo77 earlier today. Would love to hear how others feel about them!

**Comment by AriannaChau** [comment]
I LOVE the new blue! So bold without being overpowering. I'm also a big sucker for dark grey text vs black. I don't really have anything productive to say but I really really like this new direction :)

**Comment by Paul-Hebert** [comment]
These are looking great @dromo77 !

I love the new blue! It stands out more without being too in your face. It works really well with with the new semi-transparent white. It will be nice to have those semi-transparent colors, as well as the different shades of each of our main colors!

This may be out of the scope of the current explorations, but are we going to write up any guidelines about when to use which colors? Or will that be handled more at the pattern level? e.g. when would I use the pink vs the purple? When do we use the lighter or darker shades?

It would also be cool to see some element collages using some of these colors together in designs to get a better sense of how they'd mesh in a UI (though that is maybe also out of scope)

Nice job @dromo77! Really digging this overall!

**Comment by tylersticka** [comment]
Great questions, @Paul-Hebert!

> This may be out of the scope of the current explorations, but are we going to write up any guidelines about when to use which colors?

This issue won't be considered closed until the colors are represented in some form in Storybook, so we will have some documentation.

I don't know how _detailed_ that documentation will be, but it should at the very least denote what is the primary brand color, which colors are meant more for accents and emphasis, and which colors are optimized for light versus dark text, etc.

> It would also be cool to see some element collages using some of these colors together in designs to get a better sense of how they'd mesh in a UI (though that is maybe also out of scope)

Normally I'd be all over this suggestion (and @dromo77 has done some light element collage style explorations on her end, only some of which is shown here). In this case, I'm not sure it's necessary. These colors are based on what we have currently, and are intended to evolve as we author revised patterns.

I see our process as this:

1. Define the color palette in a design token file.
1. Document the palette in Storybook.
1. Start using the palette in pattern tasks.
1. Adjust palette based on actual usage.

**Comment by Paul-Hebert** [comment]
Cool, that makes sense. Thanks for the extra context @tylersticka !

**Comment by dromo77** [comment]
Thanks for the feedback! It sounds like overall reactions are positive 🎉 . Like @tylersticka  and @Paul-Hebert mentioned, I think my next steps should be to start documenting the changes in storybook.
