### ISSUE TITLE
Refined typography

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#470]
<img width="494" alt="Screen Shot 2020-02-19 at 5 23 26 PM" src="https://user-images.githubusercontent.com/69633/74891728-8ef84580-533c-11ea-856a-ec77053fa51f.png">

## Goal

In a world where variable fonts (#469) afford us more weights than we could have had before, can we _push_ sizes, weights, etc. of headings to feel more interesting and dynamic, particularly in page "heros" and article/page content?

It is _encouraged_ to refine these ideas as we continue!

## Tasks

- [x] Do design explorations of heading revisions using existing site content as a starting point
  - [x] Consider mobile-first and larger sizes
  - [x] Consider heading levels 1 through 6
  - [x] Consider ideal reading `font-size` responsively and associated line height, max content width
  - [x] Consider blockquotes, asides, introductory copy, meta copy (author info, publication date, etc.)
- [x] Determine what logic ([modular scale](https://www.modularscale.com/) or otherwise) might define type sizes relative to one another
- [x] Translate these ideas into a structure that could be interpreted by [Theo](https://github.com/salesforce-ux/theo) and used in Sass, etc.

**Comment by tylersticka** [comment]
Now that #545 is merged and #547 is drafted, I feel safe calling this issue closed.
