### ISSUE TITLE
Design token integration

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#471]
To keep things DRY and avoid the need to duplicate little updates, we should use [Theo](https://github.com/salesforce-ux/theo) to store our design tokens in a single place we can then reference from Sass or our Storybook documentation (to start with).

## Tasks

- [x] Install Theo as a dependency
- [x] Add a test YAML file for Theo to interpret (for example, a dummy color palette)
- [x] Consume those values via Sass
- [x] Display those files in an `.mdx` story

It is acceptable for this integration to be tested via dummy patterns and docs we will remove later.

**Comment by tylersticka** [comment]
This has been more challenging than expected!

I can find three examples of Theo integrating with Sass in a design system, and _none_ of them use fully up-to-date dependencies, and even though what they describe _seems_ to still work, there are enough API changes that I'm having a bear of a time figuring out why it isn't working.

Bumping the size up.

**Comment by tylersticka** [comment]
Figured it out! Replaced the Theo importer with a debug script that dumped info to a stylesheet, which made the problem easier to diagnose. Luckily ended up being something simple.

**Comment by tylersticka** [comment]
Well, I _thought_ I'd figured it out. But only for Sass. Oddly, getting the values from Theo in Storybook-land has proven very challenging.

Brain dump of issues and considerations so far...

- Theo is designed to convert from YAML or JSON to a number of formats, including Sass and HTML. But it also supports an "alias" syntax that isn't standard, so it's important to build Theo into the pipeline so those values don't go uncompiled.
- What Salesforce appears to do is convert the Theo files to various formats ahead of time via Gulp, and those files are then consumed by Storybook and other build tools. But this presents some issues:
  - They now have multiple build tools to configure and maintain.
  - The build processes are now synchronous: If Storybook runs before Theo compilation, it'll fail.
  - Updated token values take a bit longer to update in Storybook.
- Sass has a custom importer option that [can be configured to load Theo files](https://basalt.io/blog/theo-design-tokens-using-node-sass-importer-for-any-build-method), and it works really well. It's super fast and values update immediately.
- But the examples of doing that in Sass use YAML exclusively. Which is an issue because...
- ...tools to load Theo files via Webpack [in similar fashion](https://github.com/Autodesk/theo-loader) only work with JSON files. There are actually lines in the source code that _explicitly_ switch to JSON formatting.
- Even after switching Theo files to JSON, that loader appears to be abandoned, as even the baseline example raises errors.
- Attempting to call Theo directly from a story doesn't work because stories are rendered client-side, which won't have access to the file system.

I've wasted several hours and I'm now wondering if this is even the right tool for the job. Maybe this solution is over-engineered for what our needs are.

Going to give my brain a rest for now so I can attack this problem with fresh eyes another time.
