### ISSUE TITLE
List pattern(s)

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#492]
Create a list pattern. We use lists in a lot of different ways throughout the site so this may need to be multiple patterns

<img width="1277" alt="lists" src="https://user-images.githubusercontent.com/42841342/75060345-85352600-5493-11ea-96fa-25c1dfe9dedf.png">

**Comment by tylersticka** [comment]
## Tasks

- [ ] Unordered list (default `<ul>`)
- [ ] Ordered list (default `<ol>`)
- [ ] Nested lists (`<ul>` inside of `<ol>` and vice-versa)
- [ ] Unstyled list (utility for resetting?)
- [ ] Inline list
- [ ] List with count (should we still use [DotLeader](https://cloudfour-patterns.netlify.com/patterns/components/dot-leader.html) design?)
